config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  devise_for :users
  resources :products do
    resource :buy_now, only: [:show, :create], controller: :buy_now do
      get "success", on: :collection
    end
  end

  resource :cart , only: [:show, :create, :destroy] do
    get "checkout", on: :collection, to: "carts#checkout"
    post "stripe_session", on: :member, to: "carts#stripe_session"
    get "success", on: :member, to: "carts#success"
  end
  resources :users
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "products#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  belongs_to :user, optional: true 

  before_create :set_secret_id

  enum :status, ["pending", "complete"]

  private

  def set_secret_id
    self.secret_id = SecureRandom.uuid + DateTime.now.to_i.to_s
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_product, only: [:create, :destroy]

  def create
    if !@current_cart
      @current_cart = Cart.create
      session[:current_cart_id] = @current_cart.secret_id
    end
    @current_cart.cart_items.create(product_id: @product.id )
    
  end

  def show 
  end

  def checkout
    if !@current_cart&.cart_items&.any?
      redirect_to root_path, notice: "You do not have any item in your cart yet!"
    end
  end

  def stripe_session
    session = Stripe::Checkout::Session.create({
      ui_mode: 'embedded',
      line_items: [{
          # Provide the exact Price ID (e.g. pr_1234) of the product you want to sell
          price_data: {
            currency: "usd",
            unit_amount: (@current_cart.products.sum(&:price) * 100).to_i,
            product_data: {
              name: @current_cart.products.map(&:title).join(", ")
            },
          },
          quantity: 1,
        }],
        shipping_address_collection: {
          allowed_countries: STRIPE_SUPPORTED_COUNTRIES
        },
        mode: 'payment',
        return_url: success_cart_url(@current_cart.secret_id),
    })

    render json: { clientSecret: session.client_secret }
  end

  def success 
    if @current_cart.cart_items.any?
      session[:current_cart_id] = nil
    end
    @purchased_cart = Cart.find_by_secret_id(params[:id])
    redirect_to root_path if !@purchased_cart
  end

  def destroy
    @cart_item = @current_cart.cart_items.find_by_product_id(@product.id)
    @cart_item.destroy
    redirect_to cart_path(@current_cart)
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end
  
end

app/views/carts/checkout.html.erb
<div class="w-full grid md:grid-cols-2">
  <div class="w-full flex flex-col items-center md:pt-8">
    <h1 class="text-5xl font-broken text-indigo-900 text-center"> Your Cart </h1>
    <% if @current_cart&.cart_items&.any? %>
      <p> You have <%= @current_cart.cart_items.count %> products in your cart </p>
      <div class="mx-auto flex flex-col gap-2"> 
        <% @current_cart.products.each.with_index do |product, index| %>
          <div class="flex gap-2 bg-gray-700/75 p-2">
            <span class="px-2 rounded-full bg-gray-500 text-gray-100"> <%= index + 1 %> </span>
            <p class="text-indigo-100"> <%= product.title %> </p>
            <p class="text-green-500"> <%= number_to_currency product.price %> </p>
          </div>
        <% end %>
      </div>
    <% else %>
       <p> You do not have any items in your cart yet! </p>
    <% end %>
  </div>
    
  <% if @current_cart&.cart_items&.any? %>
    <div data-controller="stripe-checkout" data-stripe-checkout-url-value="<%= stripe_session_cart_path(@current_cart.secret_id) %>"> 
    </div>
  <% end %>
</div>

app/views/carts/create.turbo_stream.erb
<%= turbo_stream.update("add-to-cart", partial: "products/add_to_cart", locals: { product: @product })%>
<%= turbo_stream.update("cart", partial: "layouts/cart", locals: { cart: @current_cart }) %>

app/views/carts/show.html.erb
<div class="w-full flex flex-col items-center">
  <div class="flex justify-between w-full items-center">  
    <div class="flex flex-col gap-4">
      <h1 class="text-5xl"> Your cart </h1>
      <% if @current_cart&.cart_items&.any? %>
        <p class="text-lg"> You have <%= @current_cart.cart_items.count %> items in your cart </p>
      <% else %>
        <p class="text-lg"> You do not have any items in your cart yet </p>
      <% end %>
    </div>
    
    <% if @current_cart&.cart_items&.any? %>
      <%= link_to "Checkout Now", checkout_cart_path, class: "rounded-lg font-semibold p-4 text-center text-xl bg-yellow-400 hover:bg-yellow-500"%>
    <% else %>
      <%= content_tag :div, "Checkout Now", class: "rounded-lg font-semibold p-4 text-center text-xl bg-yellow-400 brightness-75"%> 
    <% end %>   
  </div>

  <br/>
  
  <div id="products" class="min-w-full grid md:grid-cols-4 gap-8 mb-8">
  <% if @current_cart&.cart_items&.any? %>
    <% @current_cart.products.each do |product| %>
      <div>
        <%= render "products/product", product: product %>
        <br/>
        <%= link_to "Remove from cart", cart_path(product_id: product.id), class: "p-2 rounded-lg bg-indigo-500 text-indigo-100",
            data: { turbo_method: "delete" } %>
      </div>
    <% end %>
  <% end %>
  </div>
  <br/>
  <%= link_to "Sign in to save your cart", new_user_session_path, class: "text-lg text-indigo-600 font-semibold border-b-2 border-gray-200" if !current_user %>
</div>

app/views/carts/success.html.erb
<div class="w-full flex flex-col items-center md:pt-8">
  <div class="h-[40vh] w-full mb-8 flex flex-col items-center justify-center gap-4 bg-repeat-round" >
    <h2 class="text-5xl font-semibold text-indigo-100"> Thank you for purchasing! </h2>
    <p class="text-xl font-semibold text-indigo-50"> All of your products will be shipped shortly </p> 
  </div>
  <h1 class="text-4xl font-broken text-indigo-900 text-center"> <%= @purchased_cart.products.map(&:title).join(", ") %> </h1>
  <div class="mx-auto flex flex-col gap-2"> 
    <% @purchased_cart.products.each.with_index do |product, index| %>
      <div class="flex gap-2 bg-gray-700/75 p-2">
        <span class="px-2 rounded-full bg-gray-500 text-gray-100"> <%= index + 1 %> </span>
        <p class="text-indigo-100"> <%= product.title %> </p>
        <p class="text-green-500"> <%= number_to_currency product.price %> </p>
      </div>
    <% end %>
  </div>
</div>