config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  devise_for :users
  resources :products do
    resource :buy_now, only: [:show, :create], controller: :buy_now do
      get "success", on: :collection
    end
  end

  resource :cart , only: [:show, :create, :destroy] do
    get "checkout", on: :collection, to: "carts#checkout"
    post "stripe_session", on: :member, to: "carts#stripe_session"
    get "success", on: :member, to: "carts#success"
  end
  resources :users
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
  belongs_to :category, optional: true
  has_many :cart_items 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :check_admin, except: ["index", "show"]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    new_product_params = product_params.to_unsafe_h
    new_product_params.delete("images") if new_product_params["images"].all?(&:blank?)
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id, images: [])
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_to_cart.html.erb
<div id="add-to-cart" class="w-full flex">
  <% if @current_cart && @current_cart.products.where(id: @product.id).any? %>
    <div class="rounded-lg font-semibold p-4 text-center text-xl bg-gray-400 hover:bg-gray-500 w-full">
      Already in Cart
    </div>
  <% else %>
    <%= link_to "Add To Cart", cart_path(product_id: @product.id), class: "rounded-lg font-semibold p-4 text-center text-xl bg-gray-400 hover:bg-gray-500 w-full",
        data: { turbo_method: "post" } %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id, "Category" %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name', product.category_id), { include_blank: true }, { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" } %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= link_to product do %>
  <div id="<%= dom_id product %>" class="relative flex flex-col items-center justify-center">
    <%= image_tag product.images.first, class: "w-full h-80 object-cover rounded-lg brightness-75 hover:brightness-50 transition-all duration-250" if product.images.any? %>
    <p class="text-lg text-gray-50 "> <%= product.title %> </p>
    <p class="text-lg text-gray-100"> <%= number_to_currency product.price %> </p>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to Admin", admin_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "The Best Products" %>
  <h1 class="font-bold font-nixieone text-7xl text-center text-white-700">The Best Products</h1>
  
  <div id="products" class="min-w-full grid md:grid-cols-4 gap-8">
    <% @products.each do |product| %>
    <%= render product %>
    <% end %>
  </div>

  <div class="mt-4 w-full">
    <%= link_to "Shop by Category", categories_path, class: "rounded-lg h-80 w-full bg-gray-200 text-2xl font-semibold p-2" %>
  </div>
</div>
 

app/views/products/new.html.erb
 <div class="mx-auto md:w-2/3 w-full bg-gray-200/2 p-2">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to admin", admin_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class=" w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

  <div class="max-w-7xl w-full mx-auto px-10 mb-2"> 
    <%= link_to "Products", products_path, class: "text-xl text-gray-100 hover:text-gray-200" %>
    <%= link_to "> #{@product.category.name}", @product.category, class: "text-xl text-gray-100" if @product.category %>
    <%= link_to "> #{@product.title}", @product, class: "text-xl text-gray-100" %>
  </div>

  <div class="grid md:grid-cols-2">
    <div class="max-w-md w-full mx-auto"> 
      <% if @product.images.any? %>
        <%= image_tag @product.images.first, class: "w-full h-96 object-cover" %>
        <div class="grid grid-cols-3 gap-4 mt-4"> 
          <% @product.images[1..].each do |image| %>
            <%= image_tag image, class: "w-full h-32 object-cover" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="max-w-xl flex flex-col gap-4"> 
      <h1 class="text-4xl font-broken text-indigo-900 p-4 font-urbanjungledemo"> <%= @product.title %> </h1><br>
      <div class="text-gray-700 p-4"> 
        <%= @product.description %>
      </div>
      <span class="bg-green-500 p-2 rounded-lg text-green-50 mr-auto p-2"> <%= number_to_currency @product.price %> </span>
      <div class="flex justify-between gap-8">
        <%= link_to "Buy now" , product_buy_now_path(@product) , class: "rounded-lg font-semibold p-4 bg-yellow-400 hover:bg-yellow-600 text-xl text-center mr-auto w-full " %>
        <div id="add-to-cart", class="w-full">
          <%= render "add_to_cart", product: @product %>
        </div>
      </div>
    </div>
  </div>

  <% if current_admin %>
  <div class="w-full flex justify-center items-center mt-16 gap-4">
    <%= link_to "Edit this product", edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", @product, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
  <% end %>
 </div>